'use strict'

###*
 # @ngdoc service
 # @name topMapApp.config
 # @description
 # # config
 # Constant in the topMapApp.
###
angular.module 'topMapApp'
  .constant 'sites', {
    list: [
      {code:"UK9003091",name:"Ailsa Craig",type:"SPA"},
      {code:"UK0030076",name:"Alde, Ore and Butley Estuaries",type:"SAC"},
      {code:"UK9009112",name:"Alde-Ore Estuary",type:"SPA"},
      {code:"UKMCZ0028",name:"Allonby Bay",type:"MCZ"},
      {code:"UKMCZ0001",name:"Aln Estuary",type:"MCZ"},
      {code:"UK0030387",name:"Anton Dohrn Seamount",type:"cSAC/SCI"},
      {code:"UK0030230",name:"Ascrib, Isay and Dunvegan",type:"SAC"},
      {code:"UK9014091",name:"Bae Caerfyrddin/ Carmarthen Bay",type:"SPA"},
      {code:"UK0030114",name:"Bae Cemlyn/ Cemlyn Bay",type:"SAC"},
      {code:"UK0030368",name:"Bassurelle Sandbank",type:"cSAC/SCI"},
      {code:"UKMCZ0002",name:"Beachy Head West",type:"MCZ"},
      {code:"UK9020101",name:"Belfast Lough",type:"SPA"},
      {code:"UK9020290",name:"Belfast Lough Open Water",type:"SPA"},
      {code:"UK9009171",name:"Benfleet and Southend Marshes",type:"SPA"},
      {code:"UK0017072",name:"Berwickshire and North Northumberland Coast",type:"SAC"},
      {code:"UKMCZ0029",name:"Bideford to Foreland Point",type:"MCZ"},
      {code:"UKMCZ0003",name:"Blackwater, Crouch, Roach and Colne Estuaries",type:"MCZ"},
      {code:"UK9009245",name:"Blackwater Estuary (Mid-Essex Coast Phase 4)",type:"SPA"},
      {code:"UK0030357",name:"Braemar Pockmarks",type:"SAC"},
      {code:"UK9009181",name:"Breydon Water",type:"SPA"},
      {code:"UK9002491",name:"Buchan Ness to Collieston Coast",type:"SPA"},
      {code:"UK9015011",name:"Burry Inlet",type:"SPA"},
      {code:"UK9002431",name:"Calf of Eday",type:"SPA"},
      {code:"UK9001431",name:"Canna and Sanday",type:"SPA"},
      {code:"UK9001231",name:"Cape Wrath",type:"SPA"},
      {code:"UK0012712",name:"Cardigan Bay/ Bae Ceredigion",type:"SAC"},
      {code:"UK9020161",name:"Carlingford Lough",type:"SPA"},
      {code:"UK0020020",name:"Carmarthen Bay and Estuaries/ Bae Caerfyrddin ac Aberoedd",type:"SAC"},
      {code:"UKNCMPA020",name:"Central Fladen",type:"NCMPA"},
      {code:"UK0017076",name:"Chesil and the Fleet",type:"SAC"},
      {code:"UKMCZ0004",name:"Chesil Beach and Stennis Ledges",type:"MCZ"},
      {code:"UK9010091",name:"Chesil Beach and The Fleet",type:"SPA"},
      {code:"UK9011011",name:"Chichester and Langstone Harbours",type:"SPA"},
      {code:"UKNCMPA001",name:"Clyde Sea Sill",type:"NCMPA"},
      {code:"UK9009243",name:"Colne Estuary (Mid-Essex Coast Phase 2)",type:"SPA"},
      {code:"UK9002151",name:"Copinsay",type:"SPA"},
      {code:"UK9006031",name:"Coquet Island",type:"SPA"},
      {code:"UKMCZ0030",name:"Coquet to St. Mary's",type:"MCZ"},
      {code:"UK0030381",name:"Croker Carbonate Slabs",type:"cSAC/SCI"},
      {code:"UK9001623",name:"Cromarty Firth",type:"SPA"},
      {code:"UKMCZ0031",name:"Cromer Shoal Chalk Beds",type:"MCZ"},
      {code:"UK9009244",name:"Crouch and Roach Estuaries (Mid-Essex Coast Phase 3)",type:"SPA"},
      {code:"UKMCZ0005",name:"Cumbria Coast",type:"MCZ"},
      {code:"UK0030317",name:"Darwin Mounds",type:"SAC"},
      {code:"UK9009261",name:"Deben Estuary",type:"SPA"},
      {code:"UK0030131",name:"Dee Estuary/ Aber Dyfrdwy",type:"SAC"},
      {code:"UK9009242",name:"Dengie (Mid-Essex Coast Phase 1)",type:"SPA"},
      {code:"UK0030352",name:"Dogger Bank",type:"cSAC/SCI"},
      {code:"UK9001622",name:"Dornoch Firth and Loch Fleet",type:"SPA"},
      {code:"UK0019806",name:"Dornoch Firth and Morrich More",type:"SAC"},
      {code:"UKMCZ0032",name:"Dover to Deal",type:"MCZ"},
      {code:"UKMCZ0033",name:"Dover to Folkestone",type:"MCZ"},
      {code:"UK0013031",name:"Drigg Coast",type:"SAC"},
      {code:"UK9005031",name:"Duddon Estuary",type:"SPA"},
      {code:"UK9012091",name:"Dungeness, Romney Marsh and Rye Bay",type:"SPA"},
      {code:"UK9001182",name:"East Caithness Cliffs",type:"SPA"},
      {code:"UKNCMPA002",name:"East Caithness Cliffs",type:"NCMPA"},
      {code:"UK0030364",name:"East Mingulay",type:"cSAC/SCI"},
      {code:"UKNCMPA021",name:"East of Gannet and Montrose Fields",type:"NCMPA"},
      {code:"UKMCZ0023",name:"East of Haig Fras",type:"MCZ"},
      {code:"UK0030389",name:"East Rockall Bank",type:"cSAC/SCI"},
      {code:"UK9002331",name:"East Sanday Coast",type:"SPA"},
      {code:"UK0030182",name:"Eileanan agus Sgeiran Lios mor",type:"SAC"},
      {code:"UK0013690",name:"Essex Estuaries",type:"SAC"},
      {code:"UK9010081",name:"Exe Estuary",type:"SPA"},
      {code:"UK9002091",name:"Fair Isle",type:"SPA"},
      {code:"UK0013112",name:"Fal and Helford",type:"SAC"},
      {code:"UK0017096",name:"Faray and Holm of Faray",type:"SAC"},
      {code:"UKMCZ0043",name:"Farnes East",type:"MCZ"},
      {code:"UKNCMPA022",name:"Faroe-Shetland Sponge Belt",type:"NCMPA"},
      {code:"UK9002031",name:"Fetlar",type:"SPA"},
      {code:"UKNCMPA003",name:"Fetlar to Haroldswick",type:"NCMPA"},
      {code:"UK9004411",name:"Firth of Forth",type:"SPA"},
      {code:"UKNCMPA018",name:"Firth of Forth Banks Complex",type:"NCMPA"},
      {code:"UK0030041",name:"Firth of Lorn",type:"SAC"},
      {code:"UK9004121",name:"Firth of Tay and Eden Estuary",type:"SPA"},
      {code:"UK0030311",name:"Firth of Tay and Eden Estuary",type:"SAC"},
      {code:"UK0013036",name:"Flamborough Head",type:"SAC"},
      {code:"UK9001021",name:"Flannan Isles",type:"SPA"},
      {code:"UKMCZ0006",name:"Folkestone Pomerania",type:"MCZ"},
      {code:"UK9004171",name:"Forth Islands",type:"SPA"},
      {code:"UK9002061",name:"Foula",type:"SPA"},
      {code:"UK9009246",name:"Foulness (Mid-Essex Coast Phase 5)",type:"SPA"},
      {code:"UK9002271",name:"Fowlsheugh",type:"SPA"},
      {code:"UKMCZ0046",name:"Fulmar",type:"MCZ"},
      {code:"UKMCZ0007",name:"Fylde",type:"MCZ"},
      {code:"UKNCMPA023",name:"Geikie Slide and Hebridean Slope",type:"NCMPA"},
      {code:"UK9008022",name:"Gibraltar Point",type:"SPA"},
      {code:"UK9013121",name:"Glannau Aberdaron ac Ynys Enlli/ Aberdaron Coast and Bardsey Island",type:"SPA"},
      {code:"UK0020025",name:"Glannau MÃ´n: Cors heli / Anglesey Coast: Saltmarsh",type:"SAC"},
      {code:"UK9014041",name:"Grassholm",type:"SPA"},
      {code:"UKMCZ0047",name:"Greater Haig Fras",type:"MCZ"},
      {code:"UK9003051",name:"Gruinart Flats, Islay",type:"SPA"},
      {code:"UK0030353",name:"Haig Fras",type:"SAC"},
      {code:"UK0030369",name:"Haisborough, Hammond and Winterton",type:"cSAC/SCI"},
      {code:"UK9009131",name:"Hamford Water",type:"SPA"},
      {code:"UK9001241",name:"Handa",type:"SPA"},
      {code:"UKMCZ0034",name:"Hartland Point to Tintagel",type:"MCZ"},
      {code:"UK0030388",name:"Hatton Bank",type:"cSAC"},
      {code:"UKNCMPA024",name:"Hatton-Rockall Basin",type:"NCMPA"},
      {code:"UK9002011",name:"Hermaness, Saxa Vord and Valla Field",type:"SPA"},
      {code:"UKMCZ0035",name:"Holderness Inshore",type:"MCZ"},
      {code:"UK9002141",name:"Hoy",type:"SPA"},
      {code:"UK9006111",name:"Humber Estuary",type:"SPA"},
      {code:"UK0030170",name:"Humber Estuary",type:"SAC"},
      {code:"UK9003061",name:"Inner Clyde Estuary",type:"SPA"},
      {code:"UK0030370",name:"Inner Dowsing, Race Bank and North Ridge",type:"cSAC/SCI"},
      {code:"UK9001624",name:"Inner Moray Firth",type:"SPA"},
      {code:"UK0030172",name:"Isle of May",type:"SAC"},
      {code:"UK0013694",name:"Isles of Scilly Complex",type:"SAC"},
      {code:"UKMCZ0008-01",name:"Isles of Scilly Sites: Bishop to Crim",type:"MCZ"},
      {code:"UKMCZ0008-02",name:"Isles of Scilly Sites: Bristows to the Stones",type:"MCZ"},
      {code:"UKMCZ0008-03",name:"Isles of Scilly Sites: Gilstone to Gorregan",type:"MCZ"},
      {code:"UKMCZ0008-04",name:"Isles of Scilly Sites: Hanjague to Deep Ledge",type:"MCZ"},
      {code:"UKMCZ0008-05",name:"Isles of Scilly Sites: Higher Town",type:"MCZ"},
      {code:"UKMCZ0008-06",name:"Isles of Scilly Sites: Lower Ridge to Innisvouls",type:"MCZ"},
      {code:"UKMCZ0008-07",name:"Isles of Scilly Sites: Men a Vaur to White Island",type:"MCZ"},
      {code:"UKMCZ0008-08",name:"Isles of Scilly Sites: Peninnis to Dry Ledge",type:"MCZ"},
      {code:"UKMCZ0008-09",name:"Isles of Scilly Sites: Plympton to Spanish Ledge",type:"MCZ"},
      {code:"UKMCZ0008-10",name:"Isles of Scilly Sites: Smith Sound Tide Swept Channel",type:"MCZ"},
      {code:"UKMCZ0008-11",name:"Isles of Scilly Sites: Tean",type:"MCZ"},
      {code:"UK0012566",name:"Kenfig/ Cynffig",type:"SAC"},
      {code:"UK9020221",name:"Killough Bay",type:"SPA"},
      {code:"UKMCZ0009",name:"Kingmere",type:"MCZ"},
      {code:"UK0030375",name:"Lands End and Cape Bank",type:"cSAC/SCI"},
      {code:"UK9020042",name:"Larne Lough",type:"SPA"},
      {code:"UK0014787",name:"Limestone Coast of South West Wales/ Arfordir Calchfaen de Orllewin Cymru",type:"SAC"},
      {code:"UK9006011",name:"Lindisfarne",type:"SPA"},
      {code:"UK9020294",name:"Liverpool Bay / Bae Lerpwl",type:"SPA"},
      {code:"UK0030374",name:"Lizard Point",type:"cSAC/SCI"},
      {code:"UK0030190",name:"Loch Creran",type:"SAC"},
      {code:"UKNCMPA004",name:"Loch Creran",type:"NCMPA"},
      {code:"UK0030192",name:"Loch Laxford",type:"SAC"},
      {code:"UK0030209",name:"Loch Moidart and Loch Shiel Woods",type:"SAC"},
      {code:"UK0017070",name:"Loch nam Madadh",type:"SAC"},
      {code:"UK0014749",name:"Loch of Stenness",type:"SAC"},
      {code:"UK0017074",name:"Loch Roag Lagoons",type:"SAC"},
      {code:"UKNCMPA008",name:"Lochs Duich, Long and Alsh",type:"NCMPA"},
      {code:"UK0017077",name:"Lochs Duich, Long and Alsh Reefs",type:"SAC"},
      {code:"UKNCMPA005",name:"Loch Sunart",type:"NCMPA"},
      {code:"UKNCMPA006",name:"Loch Sunart to the Sound of Jura",type:"NCMPA"},
      {code:"UKNCMPA007",name:"Loch Sween",type:"NCMPA"},
      {code:"UK9020031",name:"Lough Foyle",type:"SPA"},
      {code:"UK0013039",name:"Luce Bay and Sands",type:"SAC"},
      {code:"UKMCZ0010",name:"Lundy",type:"MCZ"},
      {code:"UK0013114",name:"Lundy",type:"SAC"},
      {code:"UK0030372",name:"Lyme Bay and Torbay",type:"cSAC/SCI"},
      {code:"UK0030371",name:"Margate and Long Sands",type:"cSAC/SCI"},
      {code:"UK9002121",name:"Marwick Head",type:"SPA"},
      {code:"UKMCZ0011",name:"Medway Estuary",type:"MCZ"},
      {code:"UK9012031",name:"Medway Estuary and Marshes",type:"SPA"},
      {code:"UK9005131",name:"Mersey Estuary",type:"SPA"},
      {code:"UK9020287",name:"Mersey Narrows and North Wirral Foreshore",type:"SPA"},
      {code:"UK9001121",name:"Mingulay and Berneray",type:"SPA"},
      {code:"UK9009101",name:"Minsmere-Walberswick",type:"SPA"},
      {code:"UK0019839",name:"Moine Mhor",type:"SAC"},
      {code:"UK0012694",name:"Monach Islands",type:"SAC"},
      {code:"UKNCMPA009",name:"Monach Isles",type:"NCMPA"},
      {code:"UK9004031",name:"Montrose Basin",type:"SPA"},
      {code:"UK9001625",name:"Moray and Nairn Coast",type:"SPA"},
      {code:"UK0019808",name:"Moray Firth",type:"SAC"},
      {code:"UK0013027",name:"Morecambe Bay",type:"SAC"},
      {code:"UK9005081",name:"Morecambe Bay",type:"SPA"},
      {code:"UKMCZ0036",name:"Mounts Bay",type:"MCZ"},
      {code:"UK0012711",name:"Mousa",type:"SAC"},
      {code:"UKNCMPA010",name:"Mousa to Boddam",type:"NCMPA"},
      {code:"UK0016612",name:"Murlough",type:"SAC"},
      {code:"UKMCZ0037",name:"Newquay and the Gannel",type:"MCZ"},
      {code:"UK9001181",name:"North Caithness Cliffs",type:"SPA"},
      {code:"UK9003171",name:"North Colonsay and Western Cliffs",type:"SPA"},
      {code:"UKNCMPA025",name:"North-east Faroe-Shetland Channel",type:"NCMPA"},
      {code:"UKMCZ0024",name:"North East of Farnes Deep",type:"MCZ"},
      {code:"UK9009031",name:"North Norfolk Coast",type:"SPA"},
      {code:"UK0019838",name:"North Norfolk Coast",type:"SAC"},
      {code:"UK0030358",name:"North Norfolk Sandbanks and Saturn Reef",type:"cSAC/SCI"},
      {code:"UK0012696",name:"North Rona",type:"SAC"},
      {code:"UK9001011",name:"North Rona and Sula Sgeir",type:"SPA"},
      {code:"UK9001051",name:"North Uist Machair and Islands",type:"SPA"},
      {code:"UK9006131",name:"Northumbria Coast",type:"SPA"},
      {code:"UKMCZ0048",name:"North-West of Jones Bank",type:"MCZ"},
      {code:"UKNCMPA019",name:"North-west Orkney",type:"NCMPA"},
      {code:"UK0030363",name:"North West Rockall Bank",type:"cSAC/SCI"},
      {code:"UKNCMPA026",name:"Norwegian Boundary Sediment Plain",type:"NCMPA"},
      {code:"UK9002081",name:"Noss",type:"SPA"},
      {code:"UKNCMPA011",name:"Noss Head",type:"NCMPA"},
      {code:"UK0017101",name:"Obain Loch Euphoirt",type:"SAC"},
      {code:"UKMCZ0049",name:"Offshore Brighton",type:"MCZ"},
      {code:"UKMCZ0044",name:"Offshore Overfalls",type:"MCZ"},
      {code:"UK0014780",name:"Orfordness - Shingle Street",type:"SAC"},
      {code:"UK9020271",name:"Outer Ards",type:"SPA"},
      {code:"UK9020309",name:"Outer Thames Estuary",type:"SPA"},
      {code:"UKMCZ0012",name:"Padstow Bay and Surrounds",type:"MCZ"},
      {code:"UKMCZ0013",name:"Pagham Harbour",type:"MCZ"},
      {code:"UK9012041",name:"Pagham Harbour",type:"SPA"},
      {code:"UK0017069",name:"Papa Stour",type:"SAC"},
      {code:"UKNCMPA012",name:"Papa Westray",type:"NCMPA"},
      {code:"UK0013116",name:"Pembrokeshire Marine/ Sir Benfro Forol",type:"SAC"},
      {code:"UK0013117",name:"Pen Llyn a`r Sarnau/ Lleyn Peninsula and the Sarnau",type:"SAC"},
      {code:"UK0030379",name:"Pisces Reef Complex",type:"cSAC/SCI"},
      {code:"UK0013111",name:"Plymouth Sound and Estuaries",type:"SAC"},
      {code:"UK0030385",name:"Pobie Bank Reef",type:"cSAC/SCI"},
      {code:"UK9010111",name:"Poole Harbour",type:"SPA"},
      {code:"UKMCZ0014",name:"Poole Rocks",type:"MCZ"},
      {code:"UK9011051",name:"Portsmouth Harbour",type:"SPA"},
      {code:"UK0030055",name:"Rathlin Island",type:"SAC"},
      {code:"UK9020011",name:"Rathlin Island",type:"SPA"},
      {code:"UK0030365",name:"Red Bay",type:"cSAC/SCI"},
      {code:"UK9005103",name:"Ribble and Alt Estuaries",type:"SPA"},
      {code:"UKNCMPA027",name:"Rosemary Bank Seamount",type:"NCMPA"},
      {code:"UK9002371",name:"Rousay",type:"SPA"},
      {code:"UK9001341",name:"Rum",type:"SPA"},
      {code:"UKMCZ0038",name:"Runnel Stone",type:"MCZ"},
      {code:"UKMCZ0039",name:"Runswick Bay",type:"MCZ"},
      {code:"UK0030069",name:"Sanday",type:"SAC"},
      {code:"UK0030354",name:"Scanner Pockmark",type:"SAC"},
      {code:"UK9015022",name:"Severn Estuary",type:"SPA"},
      {code:"UK0013030",name:"Severn Estuary/ MÃ´r Hafren",type:"SAC"},
      {code:"UK0030376",name:"Shell Flat and Lune Deep",type:"cSAC/SCI"},
      {code:"UK9001041",name:"Shiant Isles",type:"SPA"},
      {code:"UK0030383",name:"Skerries and Causeway",type:"cSAC/SCI"},
      {code:"UKMCZ0015",name:"Skerries Bank and Surrounds",type:"MCZ"},
      {code:"UK9014051",name:"Skokholm and Skomer",type:"SPA"},
      {code:"UKMCZWA0001",name:"Skomer",type:"MCZ - Wales"},
      {code:"UKNCMPA013",name:"Small Isles",type:"NCMPA"},
      {code:"UK0030386",name:"Solan Bank Reef",type:"cSAC/SCI"},
      {code:"UK0017073",name:"Solent and Isle of Wight Lagoons",type:"SAC"},
      {code:"UK9011061",name:"Solent and Southampton Water",type:"SPA"},
      {code:"UK0030059",name:"Solent Maritime",type:"SAC"},
      {code:"UK0013025",name:"Solway Firth",type:"SAC"},
      {code:"UK0019802",name:"Sound of Arisaig (Loch Ailort to Loch Ceann Traigh)",type:"SAC"},
      {code:"UK0012705",name:"Sound of Barra",type:"cSAC/SCI"},
      {code:"UKNCMPA014",name:"South Arran",type:"NCMPA"},
      {code:"UKMCZ0022",name:"South Dorset",type:"MCZ"},
      {code:"UK0030067",name:"South-East Islay Skerries",type:"SAC"},
      {code:"UK0012713",name:"South Uist Machair",type:"SAC"},
      {code:"UK9001082",name:"South Uist Machair and Lochs",type:"SPA"},
      {code:"UKMCZ0025",name:"South-West Deeps (West)",type:"MCZ"},
      {code:"UK0030061",name:"South Wight Maritime",type:"SAC"},
      {code:"UK9004271",name:"St Abb's Head to Fast Castle",type:"SPA"},
      {code:"UK0030359",name:"Stanton Banks",type:"SAC"},
      {code:"UK0030373",name:"Start Point to Plymouth Sound & Eddystone",type:"cSAC/SCI"},
      {code:"UK0013695",name:"St Kilda",type:"SAC"},
      {code:"UK9001031",name:"St Kilda",type:"SPA"},
      {code:"UK9009121",name:"Stour and Orwell Estuaries",type:"SPA"},
      {code:"UKMCZNI0001",name:"Strangford Lough",type:"MCZ - Northern Ireland"},
      {code:"UK9020111",name:"Strangford Lough",type:"SPA"},
      {code:"UK0016618",name:"Strangford Lough",type:"SAC"},
      {code:"UK0030382",name:"Studland to Portland",type:"cSAC/SCI"},
      {code:"UK9002181",name:"Sule Skerry and Sule Stack",type:"SPA"},
      {code:"UK0030273",name:"Sullom Voe",type:"SAC"},
      {code:"UK9002511",name:"Sumburgh Head",type:"SPA"},
      {code:"UK0019803",name:"Sunart",type:"SAC"},
      {code:"UKMCZ0026",name:"Swallow Sand",type:"MCZ"},
      {code:"UK9010141",name:"Tamar Estuaries Complex",type:"SPA"},
      {code:"UKMCZ0016",name:"Tamar Estuary Sites",type:"MCZ"},
      {code:"UK9006061",name:"Teesmouth and Cleveland Coast",type:"SPA"},
      {code:"UK9012021",name:"Thames Estuary and Marshes",type:"SPA"},
      {code:"UKMCZ0017",name:"Thanet Coast",type:"MCZ"},
      {code:"UK0013107",name:"Thanet Coast",type:"SAC"},
      {code:"UK9012071",name:"Thanet Coast and Sandwich Bay",type:"SPA"},
      {code:"UKNCMPA028",name:"The Barra Fan and Hebrides Terrace Seamount",type:"NCMPA"},
      {code:"UKMCZ0027",name:"The Canyons",type:"MCZ"},
      {code:"UK9013011",name:"The Dee Estuary",type:"SPA"},
      {code:"UK0030384",name:"The Maidens",type:"cSAC/SCI"},
      {code:"UKMCZ0018",name:"The Manacles",type:"MCZ"},
      {code:"UKMCZ0040",name:"The Needles",type:"MCZ"},
      {code:"UK9012011",name:"The Swale",type:"SPA"},
      {code:"UKMCZ0041",name:"The Swale Estuary",type:"MCZ"},
      {code:"UK0017068",name:"The Vadills",type:"SAC"},
      {code:"UK9008021",name:"The Wash",type:"SPA"},
      {code:"UK0017075",name:"The Wash and North Norfolk Coast",type:"SAC"},
      {code:"UKMCZ0019",name:"Torbay",type:"MCZ"},
      {code:"UK9013031",name:"Traeth Lafan/ Lavan Sands, Conway Bay",type:"SPA"},
      {code:"UK0030289",name:"Treshnish Isles",type:"SAC"},
      {code:"UK9002471",name:"Troup, Pennan and Lion's Heads",type:"SPA"},
      {code:"UKNCMPA029",name:"Turbot Bank",type:"NCMPA"},
      {code:"UK0030292",name:"Tweed Estuary",type:"SAC"},
      {code:"UKMCZ0020",name:"Upper Fowey and Pont Pill",type:"MCZ"},
      {code:"UKNCMPA015",name:"Upper Loch Fyne and Loch Goil",type:"NCMPA"},
      {code:"UK9005012",name:"Upper Solway Flats and Marshes",type:"SPA"},
      {code:"UKMCZ0042",name:"Utopia",type:"MCZ"},
      {code:"UKMCZ0050",name:"Western Channel",type:"MCZ"},
      {code:"UKNCMPA016",name:"Wester Ross",type:"NCMPA"},
      {code:"UKMCZ0045",name:"West of Walney",type:"MCZ"},
      {code:"UKNCMPA030",name:"West Shetland Shelf",type:"NCMPA"},
      {code:"UK9002101",name:"West Westray",type:"SPA"},
      {code:"UKMCZ0021",name:"Whitsand and Looe Bay",type:"MCZ"},
      {code:"UK0030380",name:"Wight-Barfleur Reef",type:"cSAC/SCI"},
      {code:"UKNCMPA017",name:"Wyre and Rousay Sounds",type:"NCMPA"},
      {code:"UK0030355",name:"Wyville Thomson Ridge",type:"cSAC/SCI"},
      {code:"UK0012687",name:"Yell Sound Coast",type:"SAC"},
      {code:"UK0030202",name:"Y Fenai a Bae Conwy/ Menai Strait and Conwy Bay",type:"SAC"},
      {code:"UK9002221",name:"Ythan Estuary, Sands of Forvie and Meikle Loch",type:"SPA"}
    ];
    
    habitatTest : [
      '697.040.001',
      'Anoxic mud with layer of silty sand',
      'Anoxic mud with shallow layer of silty sand',
      'Ascophyllum nodosum and Fucus vesiculosus growing on concrete wall and broken blocks (quadrat)',
      'Ascophyllum nodosum on concrete sea defence.',
      'Barren coarse sand bank.',
      'Barren mid shore sand with Semibalanus balanoides on occasionalûpebbles.',
      'Barren upper shore mobile sand and shingle.',
      'Buoyed rope to net bag of oysters',
      'Clay with shell debris.',
      'Clay with stones.',
      'Eroded saltmarsh step.',
      'Eulittoral clay and mixed sediment with Mytilus edulis andûbarnacles.',
      'Eulittoral mixed substrata with mussel beds.',
      'Eulittoral pool of standing water on mixed substrata.',
      'Extensive mishore mud with algal mat.',
      'Fine silt with fanworms',
      'Fine silty mud.',
      'Firm brown mud over firm grey mud with some cobbles.',
      'Firm dark grey mud.',
      'Firm mud - dark grey.',
      'floating pontoon',
      'Fluid brown mud over soft grey mud.',
      'Fluid brown mud with film on surface; some grit.',
      'Fluid brown silt over soft grey silt.',
      'Gravel and mud mix (quadrat)',
      'Gravel with some mud.',
      'Intertidal, lower estuarine mud from the mid-shore.',
      'Intertidal, lower estuarine mud from the upper shore.',
      'Intertidal, mid-estuarine mud from the mid-shore',
      'Intertidal, mid-estuarine mud from the mid-shore.',
      'Intertidal, upper estuarine mud from the lower shore.',
      'Intertidal, upper estuarine mud from the mid-shore.',
      'Intertidal, upper estuarine mussel and cockle bed on theûmid-shore.',
      'Littoral gravel and pebbles.',
      'Littoral low salinity mud with Hediste diversicolor andûoligochaetes.',
      'Littoral muddy sand and occasional boulder with Arenicolaûmarina.',
      'Littoral sandy mud with Hediste diversicolor and Macomaûbalthica.',
      'Lower shore cobbles and pebbles.',
      'Lower shore impoverished clay.',
      'Lower shore mud.',
      'Lower shore muddy cobbles.',
      'Lower shore muddy sand with shell.',
      'Lower shore muddy shells with Crepidula.',
      'Lower shore mudflat.',
      'Lower shore pebbles and sand.',
      'Lower shore sandy mud.',
      'Lower shore soft mud.',
      'Low shore clay with piddocks.',
      'Low shore mudflat.',
      'Low shore mussel bed.',
      'Low shore soft mud.',
      'Low shore well sorted gravel and coarse sand with amphipods.',
      'LS.LMu.MEst.NhomMacStr',
      'Mid and low shore reduced salinity mud with Hedisteûdiversicolor and oligichaetes.',
      'Mid shore boulders with Ascophyllum.',
      'Mid shore clay flat with occasioanl cobbles.',
      'Midshore cobbles and boulders on mixed sediment.',
      'Midshore cobbles and pebbles on sand and clay.',
      'Mid shore hard ground.',
      'Mid shore muddy pebbles.',
      'Midshore muddy shell with Mytilus.',
      'Mid shore mud flat.',
      'Midshore mudflat.',
      'Midshore mudflat dominated by Scrobicularia plana.',
      'Mid shore mud with sand and pebbles.',
      'Midshore Mytilus with pebbles.',
      'Mid shore reduced salinity mud with Hediste diversicolor andûScrobicularia plana.',
      'Mid shore sandy mud with Hediste diversicolor and Macomaûbalthica.',
      'Midshore soft mudflat.',
      'Midshore stable pebbles with mussels.',
      'Mixed muddy sediment with clay.',
      'Mixed shell sediment.',
      'Mooring chain',
      'mooring chains',
      'Mooring chains',
      'Mud',
      'Mud?',
      'Muddy mixed sediment.',
      'Muddy pebble gravel over soft to stiff mud.',
      'Muddy sand.',
      'Muddy sand and gravel, brown film.',
      'Muddy sand shore with Arenicola marina and Macoma balthica.',
      'Muddy seabed with Crepidula',
      'Mud with shell debris.',
      'Mud with shells',
      'mud with shells and pebbles',
      'mud with slipper limpets',
      'Mud with slipper limpets',
      'No description taken.',
      'Oyster raft',
      'Raft of rope mesh and plastic barrels suspended from surface',
      'Saltmarsh erosion step.',
      'Sand (with mud).',
      'Sand with mud.',
      'Sandy gravel, mixed muddy sediment.',
      'Sandy mud.',
      'Sandy/mud mixed sediment.',
      'Sandy mud, with shell debris. Fluid brown mud on surface, stiffûmud below.',
      'Sandy mud with some stones.',
      'Shell debris and mud.',
      'Shell debris, fine silt, pebbles.',
      'Shell debris with mud.',
      'Shell gravel with silt over firm mud.',
      'Shelly gravel to fluid brown mud over soft to stiff light greyûmud.',
      'Silty mud',
      'Soft brown mud.',
      'Soft brown mud over firm to soft grey mud.',
      'Soft brown mud over soft grey mud.',
      'Soft brown silt over soft to firm dark grey mud.',
      'soft mud',
      'soft mud with slipper limpets',
      'SS.SBR.PoR.SspiMx',
      'SS.SCS',
      'SS.SCS.ICS',
      'SS.SMu.SMuVS.AphTubi',
      'SS.SMu.SMuVS.AphTubi / SS.SMx.SMxVS.CreMed',
      'SS.SMu.SMuVS.NhomTubi',
      'SS.SMu.SMuVS.PolCvol',
      'SS.SMx.SMxVS.CreMed',
      'SS.SMx.SMxVS(.CreMed)',
      'SS.SSa.CMuSa.AalbNuc',
      'Stable cobbles and pebbles, barnacle dominated.',
      'Stones and shell with mud.',
      'Stones with some mud.',
      'Strandline shingle and sand.',
      'Sublittoral, lower estuarine mud.',
      'Sublittoral mud from the lower estuary.',
      'Sublittoral mud from the mid-estaury.',
      'Sublittoral mud from the mid-estuary.',
      'Sublittoral mud from the upper estuary.',
      'Thin film of brown silt over dark grey to black stiff mud.',
      'thin veneer of brown mud over dark grey mud.',
      'Upper level of ponds with Salicornia sp.',
      'Upper shore band Enteromorpha.',
      'Upper shore boulder sea defence.',
      'Upper shore cobbles with fucoid cover.',
      'Upper shore Fucus? ceranoides band.',
      'Upper shore Fucus ceranoides on concrete sea defence.',
      'Upper shore muddy boulders.',
      'Upper shore muddy sand with Arenicola marina.',
      'Upper shore muddy shingle and pebbles.',
      'Upper shore mudflat.',
      'Upper shore shingle.',
      'Upper shore shingle bank.',
      'Upper shore soft mud.',
      'Very soft lower shore mud.',
      'wooden pilings'
    ];
    speciesTest: [
      'Abietinaria abietina',
      'Abludomelita obtusata',
      'Abra',
      'Abra alba',
      'Abra nitida',
      'Abra prismatica',
      'Abra tenuis',
      'Abyssoninoe',
      'Acanthodoris pilosa',
      'Acari',
      'Achelia',
      'Achelia echinata',
      'Actiniaria',
      'Actinopterygii',
      'Aeolidiidae',
      'Aequipecten opercularis',
      'Agonus cataphractus',
      'Alcyonidioides mytili',
      'Alcyonidium diaphanum',
      'Alcyonidium gelatinosum',
      'Alcyonidium parasiticum',
      'Alderina imbellis',
      'Alitta virens',
      'Amathia lendigera',
      'Ammothea hilgendorfi',
      'Ammotheidae',
      'Ammothella longipes',
      'Ampelisca',
      'Ampelisca brevicornis',
      'Ampelisca diadema',
      'Ampelisca spinipes',
      'Ampelisca tenuicornis',
      'Ampharete',
      'Ampharete baltica',
      'Ampharete finmarchica',
      'Ampharete grubei',
      'Ampharete lindstroemi',
      'Ampharetidae',
      'Amphibalanus improvisus',
      'Amphiblestrum auritum',
      'Amphicteis gunneri',
      'Amphicteis midas',
      'Amphilectus fucorum',
      'Amphilochus manudens',
      'Amphilochus neapolitanus',
      'Amphilochus tenuimanus',
      'Amphipholis squamata',
      'Amphipoda',
      'Amphiuridae',
      'Anapagurus laevis',
      'Ancula gibbosa',
      'Anguinella palmata',
      'Anoplodactylus petiolatus',
      'Anoplodactylus pygmaeus',
      'Antedon bifida',
      'Anthoathecata',
      'Anthura gracilis',
      'Anurida maritima',
      'Aonides oxycephala',
      'Aora gracilis',
      'Aoridae',
      'Aphelochaeta',
      'Aphelochaeta marioni',
      'Apherusa bispinosa',
      'Aphrodita aculeata',
      'Aphroditidae',
      'Aplidium',
      'Aplidium nordmanni',
      'Arachnida',
      'Arenicola marina',
      'Arenicolidae',
      'Argissa hamatipes',
      'Aricidea (Acmira) catherinae',
      'Aricidea (Aricidea) minuta',
      'Ascidiacea',
      'Ascidia conchilega',
      'Ascidia mentula',
      'Ascidicola rosea',
      'Ascidiella',
      'Ascidiella aspersa',
      'Ascidiella scabra',
      'Asclerocheilus intermedius',
      'Ascophyllum nodosum',
      'Aspidelectra melolontha',
      'Asterias rubens',
      'Astropecten irregularis',
      'Audouinella',
      'Aurelia aurita',
      'Austrominius modestus',
      'Axionice maculata',
      'Balanidae',
      'Balanus crenatus',
      'Baltidrilus costatus',
      'Barentsia',
      'Barnea candida',
      'Bathyporeia',
      'Bathyporeia elegans',
      'Beroe cucumis',
      'Bicellariella ciliata',
      'Bivalvia',
      'Bodotria arenosa',
      'Bodotria scorpioides',
      'Botrylloides',
      'Botrylloides leachii',
      'Botrylloides violaceus',
      'Botryllus schlosseri',
      'Bougainvillia muscus',
      'Bougainvilliidae',
      'Bowerbankia',
      'Bowerbankia citrina',
      'Bowerbankia gracillima',
      'Bowerbankia imbricata',
      'Bowerbankia pustulosa',
      'Bradypontius',
      'Branchiopoda',
      'Bryopsis',
      'Bryopsis hypnoides',
      'Bryopsis plumosa',
      'Bryozoa',
      'Bryozoa indet crusts',
      'Buccinum undatum',
      'Bugula flabellata',
      'Bugula plumosa',
      'Bugula turbinata',
      'Callionymus',
      'Callionymus reticulatus',
      'Callipallene',
      'Callipallene brevirostris',
      'Calycella syringa',
      'Campanularia hincksii',
      'Campanulariidae',
      'Cancer pagurus',
      'Capitella',
      'Capitella capitata',
      'Caprella',
      'Caprella equilibra',
      'Caprella linearis',
      'Capsosiphon fulvescens',
      'Carcinus maenas',
      'Caryophyllia (Caryophyllia) smithii',
      'Caulleriella',
      'Caulleriella alata',
      'Caulleriella bioculata',
      'Caulleriella killariensis',
      'Caulleriella zetlandica',
      'Ceramium',
      'Ceramium virgatum',
      'Cerastoderma edule',
      'Cerianthus lloydii',
      'Chaetomorpha linum',
      'Chaetozone gibber',
      'Chaetozone setosa',
      'Cheirocratus',
      'Cheirocratus intermedius',
      'Cheirocratus sundevalli',
      'Chlorophyta',
      'Chondrus crispus',
      'Chrysallida pellucida',
      'Chrysaora hysoscella',
      'Chthamalus montagui',
      'Ciona intestinalis',
      'Cirratulus',
      'Cirratulus caudatus',
      'Cirratulus cirratus',
      'Cirriformia',
      'Cirriformia tentaculata',
      'Cirripedia',
      'Cladophora',
      'Cladophora rupestris',
      'Cladostephus spongiosus',
      'Clausinella fasciata',
      'Clavelina lepadiformis',
      'Cliona',
      'Cliona celata',
      'Clymenella cincta',
      'Clytia hemisphaerica',
      'Coleoptera',
      'Collembola',
      'Colpomenia peregrina',
      'Conopeum reticulum',
      'Copepoda',
      'Corallinaceae',
      'Corallina officinalis',
      'Corella eumyota',
      'Corophium',
      'Corophium volutator',
      'Cossura',
      'Cossura longocirrata',
      'Cradoscrupocellaria reptans',
      'Crangon crangon',
      'Crassicorophium crassicorne',
      'Crassostrea gigas',
      'Crepidula fornicata',
      'Crossaster papposus',
      'Cryptopleura ramosa',
      'Cryptosula pallasiana',
      'Cumella (Cumella) pygmaea',
      'Cumopsis goodsir',
      'Cuthona',
      'Cyanobacteria',
      'Cyathura carinata',
      'Cyclopoida',
      'Cystoclonium purpureum',
      'Decapoda',
      'Dendrodoa grossularia',
      'Dexamine spinosa',
      'Dexamine thea',
      'Diadumene cincta',
      'Diastylis bradyi',
      'Diastylis rathkei',
      'Diastylis rugosa',
      'Diatoms film',
      'Dictyota dichotoma',
      'Didemnidae',
      'Didemnum',
      'Didemnum maculosum',
      'Diplodonta rotundata',
      'Diplosoma listerianum',
      'Diplosoma spongiforme',
      'Dipolydora caulleryi',
      'Dipolydora coeca',
      'Dipolydora quadrilobata',
      'Distaplia rosea',
      'Dodecaceria',
      'Donax vittatus',
      'Doto',
      'Doto coronata',
      'Dynamena pumila',
      'Dyopedos monacantha',
      'Dysidea fragilis',
      'Echinogammarus incertae sedis planicrurus',
      'Echinus esculentus',
      'Ectocarpaceae',
      'Ectopleura larynx',
      'Edwardsia claparedii',
      'Edwardsiidae',
      'Electra monostachys',
      'Electra pilosa',
      'Elysia viridis',
      'Enchytraeidae',
      'Encrusting green algae',
      'Ennucula tenuis',
      'Ensis',
      'Ensis directus',
      'Enteropneusta',
      'Epilepton clarkiae',
      'Epitonium clathratulum',
      'Erinaceusyllis erinaceus',
      'Eriocheir sinensis',
      'Erythroglossum laciniatum',
      'Escharella immersa',
      'Escharella ventricosa',
      'Eteone',
      'Eteone barbata',
      'Eteone longa',
      'Eualus cranchii',
      'Eualus pusiolus',
      'Eubranchus',
      'Eubranchus tricolor',
      'Euclymene',
      'Euclymene oerstedi',
      'Eucratea loricata',
      'Eudendrium',
      'Eudorella truncatula',
      'Eulalia bilineata',
      'Eulalia expusilla',
      'Eulalia ornata',
      'Eulalia viridis',
      'Eumida bahusiensis',
      'Eumida sanguinea',
      'Eunereis longissima',
      'Eunicella verrucosa',
      'Eupolymnia nesidensis',
      'Eurydice pulchra',
      'Eusarsiella zostericola',
      'Eusyllis blomstrandi',
      'Exogone (Exogone) naidina',
      'Exogone (Exogone) verugera',
      'Farrella repens',
      'Filamentous green algae',
      'Filifera',
      'Flabelligera affinis',
      'Flustra foliacea',
      'Foliose red algae',
      'Fucus',
      'Fucus ceranoides',
      'Fucus spiralis',
      'Fucus vesiculosus',
      'Galathowenia oculata',
      'Gammarellus homari',
      'Gammaridae',
      'Gammaridea',
      'Gammaropsis cornuta',
      'Gammaropsis maculata',
      'Gammarus',
      'Gammarus locusta',
      'Garveia nutans',
      'Gattyana cirrhosa',
      'Gibbula',
      'Gibbula cineraria',
      'Gitana sarsi',
      'Glycera',
      'Glycera alba',
      'Glycera tridactyla',
      'Glycinde nordmanni',
      'Glycymeris glycymeris',
      'Gnathiidae',
      'Gobiidae',
      'Gobiusculus flavescens',
      'Gobius niger',
      'Gobius paganellus',
      'Golfingia (Golfingia) elongata',
      'Golfingia (Golfingia) vulgaris vulgaris',
      'Goneplax rhomboides',
      'Goniada maculata',
      'Gracilaria',
      'Gracilaria gracilis',
      'Grania',
      'Grantia compressa',
      'Halecium',
      'Halecium halecinum',
      'Halichondria (Halichondria) bowerbanki',
      'Halichondria (Halichondria) panicea',
      'Haliclona (Haliclona) oculata',
      'Halisarca dujardinii',
      'Halopteris catharina',
      'Halurus flosculosus',
      'Harmothoe',
      'Harmothoe antilopes',
      'Harmothoe extenuata',
      'Harmothoe imbricata',
      'Harmothoe impar',
      'Harpinia',
      'Harpinia antennaria',
      'Harpinia crenulata',
      'Harpinia pectinata',
      'Hediste diversicolor',
      'Hemichordata',
      'Hemimycale columella',
      'Hesionidae',
      'Heteroclymene robusta',
      'Hexacorallia',
      'Hilbigneris gracilis',
      'Hildenbrandia rubra',
      'Hippolyte varians',
      'Hippolytidae',
      'Holothuria (Panningothuria) forskali',
      'Hyas araneus',
      'Hydrallmania falcata',
      'Idotea',
      'Idotea chelipes',
      'Idotea linearis',
      'Idotea pelagica',
      'Inachus',
      'Insecta',
      'Iphimedia minuta',
      'Jaera (Jaera) nordmanni',
      'Janira maculosa',
      'Janolus cristatus',
      'Jassa',
      'Jassa falcata',
      'Kefersteinia cirrata',
      'Kurtiella bidentata',
      'Lagis koreni',
      'Lagotia viridis',
      'Laminaria hyperborea',
      'Lanice conchilega',
      'Laomedea angulata',
      'Laomedea flexuosa',
      'Lekanesphaera monodi',
      'Lepidochitona (Lepidochitona) cinerea',
      'Lepidonotus squamatus',
      'Leptochiton asellus',
      'Leptoplana tremellaris',
      'Leucandra ananas',
      'Leucosolenia',
      'Levinsenia gracilis',
      'Limanda limanda',
      'Liocarcinus',
      'Liocarcinus holsatus',
      'Liocarcinus navigator',
      'Liparis',
      'Littorina fabalis',
      'Littorina littorea',
      'Littorina obtusata',
      'Littorina saxatilis',
      'Lomentaria articulata',
      'Lomentaria clavellosa',
      'Lovenella clausa',
      'Loxosomella',
      'Loxosomella phascolosomata',
      'Lumbrineris latreilli',
      'Lysidice unicornis',
      'Macoma balthica',
      'Macropodia',
      'Macropodia rostrata',
      'Mactra stultorum',
      'Maerella tenuimana',
      'Magelona filiformis',
      'Malacoceros fuliginosus',
      'Malmgreniella arenicolae',
      'Malmgreniella lunulata',
      'Manayunkia aestuarina',
      'Marphysa bellii',
      'Marphysa sanguinea',
      'Marthasterias glacialis',
      'Mastocarpus stellatus',
      'Mediomastus fragilis',
      'Melinna',
      'Melinna palmata',
      'Melita palmata',
      'Membraniporella nitida',
      'Mercenaria mercenaria',
      'Merlangius merlangus',
      'Mesopodopsis',
      'Mesopodopsis slabberi',
      'Metopa propinqua',
      'Microdeutopus anomalus',
      'Microdeutopus chelifer',
      'Microdeutopus gryllotalpa',
      'Microphthalmus',
      'Microprotopus maculatus',
      'Microspio',
      'Mimachlamys varia',
      'Modiolus',
      'Modiolus modiolus',
      'Molgula',
      'Molgula manhattensis',
      'Monocorophium acherusicum',
      'Monopseudocuma gilsoni',
      'Monopylephorus irroratus',
      'Montacuta substriata',
      'Monticellina',
      'Munna',
      'Musculus niger',
      'Musculus subpictus',
      'Mya arenaria',
      'Mya truncata',
      'Mycale',
      'Myodocopida',
      'Myoidea',
      'Myrianida',
      'Myriochele heeri',
      'Mysida',
      'Mysta picta',
      'Mytilidae',
      'Mytilus edulis',
      'Nais',
      'Nannastacus unguiculatus',
      'Necora puber',
      'Nematoda',
      'Nemertea',
      'Neoamphitrite figulus',
      'Neomysis integer',
      'Neosiphonia harveyi',
      'Nephrops norvegicus',
      'Nephtys',
      'Nephtys caeca',
      'Nephtys cirrosa',
      'Nephtys hombergii',
      'Nephtys kersivalensis',
      'Nereis zonata',
      'Nicolea venustula',
      'Nicolea zostericola',
      'Noemiamea dolioliformis',
      'Nolella',
      'Notodelphys',
      'Notomastus',
      'Nototropis guttatus',
      'Nototropis swammerdamei',
      'Nucula',
      'Nucula nitidosa',
      'Nucula nucleus',
      'Nuculidae',
      'Nudibranchia',
      'Nymphon',
      'Nymphon brevirostre',
      'Nymphon gracile',
      'Nymphon grossipes',
      'Nymphon hirtum',
      'Obelia',
      'Obelia dichotoma',
      'Obelia longissima',
      'Odostomia',
      'Odostomia plicata',
      'Odostomia turrita',
      'Oligochaeta',
      'Onchidoris',
      'Onchidoris muricata',
      'Ophelia borealis',
      'Ophiocomina nigra',
      'Ophiothrix',
      'Ophiothrix fragilis',
      'Ophiura',
      'Ophiura albida',
      'Ophiura ophiura',
      'Ophiuridae',
      'Orchomene humilis',
      'Ostracoda',
      'Ostrea edulis',
      'Paguridae',
      'Pagurus',
      'Pagurus bernhardus',
      'Palaemon longirostris',
      'Palaemon serratus',
      'Palmaria palmata',
      'Pandalus montagui',
      'Paracentrotus lividus',
      'Paradoneis lyra',
      'Paramphitrite tetrabranchia',
      'Paranais litoralis',
      'Paranymphon spinosum',
      'Parexogone hebes',
      'Pariambus typicus',
      'Parvicardium exiguum',
      'Parvicardium minimum',
      'Parvicardium scabrum',
      'Patella vulgata',
      'Pecten maximus',
      'Pedicellina',
      'Peringia ulvae',
      'Perioculodes longimanus',
      'Perophora listeri',
      'Petricolaria pholadiformis',
      'Phaxas pellucidus',
      'Pherusa flabellata',
      'Pherusa plumosa',
      'Phialella quadrata',
      'Philine',
      'Philocheras trispinosus',
      'Phisidia aurea',
      'Pholoe baltica',
      'Pholoe inornata',
      'Phoronis',
      'Phoronis muelleri',
      'Photis longicaudata',
      'Photis pollex',
      'Photis reinhardi',
      'Phoxichilidium femoratum',
      'Phtisica marina',
      'Phyllodoce mucosa',
      'Pinnotheres pisum',
      'Pionosyllis',
      'Pisces',
      'Pisidia longicornis',
      'Plagioecia sarniensis',
      'Platynereis dumerilii',
      'Pleurobrachia pileus',
      'Pleurocrypta',
      'Plocamium cartilagineum',
      'Plumaria plumosa',
      'Plumularia setacea',
      'Plumulariidae',
      'Polycarpa',
      'Polycarpa fibrosa',
      'Polycarpa pomaria',
      'Polycarpa scuba',
      'Polychaeta',
      'Polycirrus',
      'Polydora',
      'Polydora ciliata',
      'Polydora cornuta',
      'Polyides rotunda',
      'Polyplacophora',
      'Polysiphonia',
      'Polysiphonia elongata',
      'Polysiphonia fucoides',
      'Pomatoschistus',
      'Pomatoschistus minutus',
      'Pomatoschistus pictus',
      'Porania (Porania) pulvillus',
      'Porifera',
      'Porifera indet crusts',
      'Porphyra',
      'Potamopyrgus antipodarum',
      'Prionospio fallax',
      'Proceraea',
      'Procerastea',
      'Prosphaerosyllis tetralix',
      'Protocirrineris',
      'Protodorvillea kefersteini',
      'Protozoa',
      'Psamathe fusca',
      'Psammechinus miliaris',
      'Pseudocuma (Pseudocuma) longicorne',
      'Pterothamnion plumula',
      'Pusillina inconspicua',
      'Pycnogonida',
      'Pycnogonidae',
      'Pycnogonum litorale',
      'Pygospio elegans',
      'Retusa obtusa',
      'Rhodophyllis divaricata',
      'Rhodophyta',
      'Rissoa parva',
      'Ruditapes philippinarum',
      'Sabella pavonina',
      'Sabellaria spinulosa',
      'Saccharina latissima',
      'Saccorhiza polyschides',
      'Sagartia',
      'Sagartia elegans',
      'Sagartia troglodytes',
      'Salicornia',
      'Salvatoria clavata',
      'Sargassum muticum',
      'Scalibregma celticum',
      'Scalibregma inflatum',
      'Schistomysis kervillei',
      'Schizomavella auriculata',
      'Scoletoma magnidentata',
      'Scoloplos (Scoloplos) armiger',
      'Scrobicularia plana',
      'Scrupocellaria',
      'Scrupocellaria scruposa',
      'Semibalanus balanoides',
      'Sepia officinalis',
      'Sertularella',
      'Sertularia',
      'Sertularia cupressina',
      'Sertularia distans',
      'Solaster endeca',
      'Sphaerodoridium',
      'Sphaerodoropsis minuta',
      'Sphaeroma',
      'Sphaerosyllis',
      'Sphaerosyllis bulbosa',
      'Sphaerosyllis hystrix',
      'Sphaerosyllis taylori',
      'Spio armata',
      'Spio filicornis',
      'Spio martinensis',
      'Spiophanes bombyx',
      'Spirobranchus',
      'Spirobranchus lamarcki',
      'Spisula',
      'Spisula subtruncata',
      'Staphylinidae',
      'Stelligera rigida',
      'Stenothoe marina',
      'Sthenelais boa',
      'Streblospio',
      'Streblospio shrubsolii',
      'Streptosyllis websteri',
      'Styela clava',
      'Suberites carnosus',
      'Sycon ciliatum',
      'Syllidae',
      'Syllides',
      'Syllides benedicti',
      'Syllidia armata',
      'Syllis',
      'Syllis armillaris',
      'Syllis gracilis',
      'Symphodus melops',
      'Syngnathus acus',
      'Syngnathus rostellatus',
      'Tanaissus lilljeborgi',
      'Tanaopsis graciloides',
      'Tapes',
      'Tellinidae',
      'Tenellia adspersa',
      'Terebellidae',
      'Tharyx',
      'Thecacera pennigera',
      'Thelepus cincinnatus',
      'Thracia',
      'Thyone',
      'Thyone fusus',
      'Thysanocardia procera',
      'Timoclea ovata',
      'Trididemnum cereum',
      'Tritaeta gibbosa',
      'Tryphosella sarsi',
      'Tubificoides',
      'Tubificoides amplivasatus',
      'Tubificoides benedii',
      'Tubificoides insularis',
      'Tubificoides pseudogaster',
      'Tubificoides swirencoides',
      'Tubularia indivisa',
      'Tubulariidae',
      'Turbellaria',
      'Turritella communis',
      'Ulva',
      'Ulva clathrata',
      'Ulva lactuca',
      'Ulva linza',
      'Unciola crenatipalma',
      'Undaria pinnatifida',
      'Urticina eques',
      'Urticina felina',
      'Vaunthompsonia cristata',
      'Vertebrata lanosa',
      'Vesicularia spinosa',
      'Walkeria uva'
    ];
}
